import { fromEvent, map, tap } from 'rxjs';

const text = document.createElement('div');
text.innerHTML = `
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio ut non officia a quae veniam, rem corrupti explicabo, quas sed cupiditate. Quam doloremque atque quibusdam possimus dolor? Maxime, repellendus non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores veritatis voluptatibus neque autem molestias tempore, dolorem voluptatum aliquam, ad possimus odit deserunt pariatur esse fugiat sapiente doloribus, provident cumque optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis harum excepturi possimus ipsam magnam saepe neque, minima delectus tempore, quia, iusto alias sed itaque. Nostrum nihil repellendus reiciendis nesciunt non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos at exercitationem nam vero, id nobis consectetur. Modi voluptatem impedit iure voluptatibus culpa repellat ipsa, nihil praesentium inventore. Dolorum, deleniti esse. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem debitis, quos facilis esse, delectus aspernatur adipisci tempore voluptates, 
laborum dolores rerum. Ducimus eum necessitatibus quaerat iure quos rem cum? Eligendi!
<br /> <br /> <br /> <br />
`;

const body = document.querySelector('body');
body.appendChild(text);

const progressBar = document.createElement('div');
progressBar.classList.add('progress-bar');
body.appendChild(progressBar);

// Function to calc
const calcPercentageScroll = (event: any) => {
  const { scrollTop, scrollHeight, clientHeight } =
    event.target.documentElement;
  const percentage = (scrollTop / (scrollHeight - clientHeight)) * 100;
  return `${percentage}%`;
};

// Streams
const scroll$ = fromEvent(document, 'scroll');
// scroll$.subscribe(console.log)

const progress$ = scroll$.pipe(
  map((event) => calcPercentageScroll(event)),
  // tap(console.log)
);

progress$.subscribe((percentage) => {
  progressBar.style.width = percentage;
});
